import "./globals.css"
import Navbar from "./components/Navbar/index"
import Footer from "./components/Footer/index"

export const metadata = {
  title: "Smilez",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
     
        {children}
      
      </body>
    </html>
  )
}
